In [1]:
import numpy as np
import pandas as pd

In [9]:
def generate_campaign_data(n_users=5000, random_state=42):
    np.random.seed(random_state)

    user_ids = np.arange(1, n_users + 1)

    segments = np.random.choice(
        ["high", "medium", "low"],
        size=n_users,
        p=[0.2, 0.5, 0.3]
    )

    engagement_score = []

    for seg in segments:
        if seg == "high":
            engagement_score.append(np.random.uniform(0.6, 1.0))
        elif seg == "medium":
            engagement_score.append(np.random.uniform(0.3, 0.7))
        else:
            engagement_score.append(np.random.uniform(0.0, 0.5))

    engagement_score = np.array(engagement_score)

    past_purchase_count = np.random.poisson(lam=3, size=n_users)

    avg_order_value = np.random.normal(loc=500, scale=100, size=n_users)
    avg_order_value = np.clip(avg_order_value, 100, None)  # no negative/too small values


    # Email Opened
    open_prob = engagement_score * 0.8
    email_opened = np.random.binomial(1, open_prob)

    # Clicked (only if opened)
    click_prob = engagement_score * 0.6
    clicked = np.random.binomial(1, click_prob) * email_opened

    # Converted (only if clicked)
    convert_prob = engagement_score * 0.5
    converted = np.random.binomial(1, convert_prob) * clicked

    revenue_multiplier = np.random.uniform(0.8, 1.2, size=n_users)
    revenue = converted * avg_order_value * revenue_multiplier

    campaign_cost = np.full(n_users, 10)

    df = pd.DataFrame({
        "user_id": user_ids,
        "segment": segments,
        "engagement_score": engagement_score,
        "past_purchase_count": past_purchase_count,
        "avg_order_value": avg_order_value,
        "email_opened": email_opened,
        "clicked": clicked,
        "converted": converted,
        "campaign_cost": campaign_cost,
        "revenue": revenue
    })

    return df

In [10]:
df = generate_campaign_data()
df.head()

,user_id,segment,engagement_score,past_purchase_count,avg_order_value,email_opened,clicked,converted,campaign_cost,revenue
0,1,medium,0.457454,2,606.395585,0,0,0,10,0.0
1,2,low,0.236718,3,458.504412,0,0,0,10,0.0
2,3,low,0.427274,7,301.914615,0,0,0,10,0.0
3,4,medium,0.436002,0,463.612920,0,0,0,10,0.0
4,5,high,0.947860,0,337.356924,1,0,0,10,0.0

In [12]:
df.tail()

,user_id,segment,engagement_score,past_purchase_count,avg_order_value,email_opened,clicked,converted,campaign_cost,revenue
4995,4996,low,0.428828,3,396.450814,0,0,0,10,0.0
4996,4997,high,0.959004,1,465.032090,1,0,0,10,0.0
4997,4998,medium,0.678683,1,370.011509,1,0,0,10,0.0
4998,4999,low,0.198744,1,482.916197,0,0,0,10,0.0
4999,5000,medium,0.386856,3,515.011797,0,0,0,10,0.0

In [23]:
df.shape

(5000, 10)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user_id              5000 non-null   int64
 1   segment              5000 non-null   object
 2   engagement_score     5000 non-null   float64
 3   past_purchase_count  5000 non-null   int32
 4   avg_order_value      5000 non-null   float64
 5   email_opened         5000 non-null   int32
 6   clicked              5000 non-null   int32
 7   converted            5000 non-null   int32
 8   campaign_cost        5000 non-null   int64
 9   revenue              5000 non-null   float64
dtypes: float64(3), int32(4), int64(2), object(1)
memory usage: 312.6+ KB

In [19]:
df["segment"].value_counts(normalize=True)

segment
medium    0.5002
low       0.2940
high      0.2058
Name: proportion, dtype: float64

In [20]:
# conversion rate
df["converted"].mean()

np.float64(0.0406)

In [21]:
# open rate
df["email_opened"].mean()

np.float64(0.3868)

In [22]:
# CTR
df["clicked"].mean()

np.float64(0.1348)